spring:
  jackson:
    default-property-inclusion: non_empty
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8090
  servlet:
    application-display-name: Legal Agreement Service



